---
- name: Finding physical switchport and path
  hosts: "{{ target }}"
  strategy: free
  connection: network_cli
  gather_facts: no 

  vars:
    ansible_network_os: ios
    get_mac_vlan: ~/dev/src/ansible_networking/parsers/get_mac_vlan.yaml
  
 # vars_prompt:
 #  - name: "ansible_user"
 #    prompt: "Username"
 #    private: no 
 #  - name: "ansible_ssh_pass"
 #    prompt: "Password"
  
  tasks:
    - name: network-engine roles
      import_role:
        name: ansible-network.network-engine
    - ios_facts:
        gather_subset: interfaces
      register: switch_info
    - name: Get MAC from IP
      ios_command:
        commands:
          - "show ip arp {{ IP }}"
      register: ip_mac
    - name: parse the sh ip arp output
      command_parser:
        file: "{{ get_mac_vlan }}"
        content: "{{ ip_mac.stdout[0] }}"
    - name: set output facts for switch mac address
      set_fact:
        switch_mac_addr: " {{ switch_info.ansible_facts.ansible_net_interfaces.Vlan1.macaddress }} "
    - name: traceroute the mac address
      ios_command:
        commands:
          - "traceroute mac {{ switch_mac_addr }} {{ mac_addr_facts.mac_addr }} vlan {{ mac_addr_facts.vlan }} detail"
      register: traceroute_output
    - name: Display the results
      debug: 
        var: traceroute_output.stdout_lines


